### PR TITLE
Contrast 3 emojis

### LINKED ISSUE #395: Contrast more emojis
Remake contrast emoji.
🌬 U+1F32C Wind blowing face
🦷 U+1F9B7 Tooth
🪄 U+1FA84 Magic wand
🪅 U+1FA85 Pinata
🪿 U+1FABF Goose

### PR DESCRIPTION
**Pull request by nataliakeniganti**
Fixes #395

### CODE REVIEW

**Comment by Mercury13** [comment]
May I decline? The job is too basic.

**Comment by nataliakeniganti** [comment]
> May I decline? The job is too basic.

Merge my pull request?

**Comment by Mercury13** [comment]
Cool or you can do better?

**Comment by Mercury13** [comment]
image

**Pull request closed without merging**
